# Generated by Django 5.1.1 on 2024-12-20 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 12, 20, 16, 21, 0, 954111, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
